### PR TITLE
Changes for Python 3

### PR DESCRIPTION
**Pull request by chapatiyaq**
Based on the pull request #7 from @scls19fr (I changed one more line)

### CODE REVIEW

**Comment by scls19fr** [comment]
Does is pass unit test https://github.com/rbaron/omr/issues/9 ?

**Comment by chapatiyaq** [comment]
Yes, it does:

```
$ pytest
============================= test session starts =============================
platform win32 -- Python 3.6.4, pytest-3.6.1, py-1.5.3, pluggy-0.6.0
rootdir: H:\Ma\omr, inifile:
collected 1 item

test_omr.py .                                                            [100%]

========================== 1 passed in 0.65 seconds ===========================
```

**Comment by scls19fr** [comment]
Good!
Moreover same code works both with Python 3 and Python 2
@rbaron can we have this code be merged?

**Comment by rbaron** [comment]
Awesome. Thanks @chapatiyaq & @scls19fr.

**Pull request merged**
